[project]
name = "speculative-decoding-llama3"
version = "0.1"
description = "Llama3 implemented in python step by step, from scratch"
requires-python = ">=3.10"

dependencies = [
    "hf-transfer>=0.1.9",
    "torch>=2.8.0",
    "transformers>=4.56.0",
]
